/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connect.ConnectDB1;
import entity.CongNhan;
import entity.BangCongCN;
import entity.LuongCongNhan;
import javax.swing.table.DefaultTableModel;
import dao.LuongCNDAO;
import dao.ChamCongCNDAO;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import java.sql.Date;
import java.text.DecimalFormat;
import java.util.Hashtable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author admin
 */
public class FrmLuongCN extends javax.swing.JPanel {

    LuongCNDAO luongcndao;
    ChamCongCNDAO ccdao;
    DefaultTableModel modelLuong;
    LocalDate today;
    DefaultTableModel modelCN;

    /**
     * Creates new form TinhLuongCN
     */
    public FrmLuongCN() {
        initComponents();
        try {
            ConnectDB1.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        modelCN = (DefaultTableModel) tblCN.getModel();
        modelLuong = (DefaultTableModel) tblLuong.getModel();
        ccdao = new ChamCongCNDAO();
        luongcndao = new LuongCNDAO();
        loadComboBoxThang();
        loadComboBoxNam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void readTableCN() {
        modelCN.setRowCount(0);
        String thang = cbothang.getSelectedItem().toString();
        String nam = cbonam.getSelectedItem().toString();
        List<BangCongCN> lst = luongcndao.getALLCNCC(thang, nam);
        //SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        for (BangCongCN bc : lst) {
            Object[] row = {bc.getMaCN().getMaCN(), bc.getTenCN().getTenCN()};
            modelCN.addRow(row);

        }

    }

    public void clickTableCN() {
        int row = tblCN.getSelectedRow();
        txtMaCN.setText(modelCN.getValueAt(row, 0).toString());
        txtTenCN.setText(modelCN.getValueAt(row, 1).toString());
        String macn = modelCN.getValueAt(row, 0).toString();
        String thang = cbothang.getSelectedItem().toString();
        int slld = luongcndao.findSLSPLamDuoc(macn,thang);
        txtSoSPLamDuoc.setText("" + slld);
        int scld = luongcndao.findSoCaLamDuoc(macn,thang);
        txtSoCaDaLam.setText("" + scld);
        int sltc = luongcndao.findSoCaTang(macn,thang);
        txtSoCaTang.setText("" + sltc);

    }

    public void loadComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbonam.getModel();
        model.removeAllElements();
        List<String> lst = luongcndao.getALLNamCC();
        for (String string : lst) {
            model.addElement(string);
        }
        model.addElement("");
        cbonam.setSelectedIndex(0);
    }

    public void loadComboBoxThang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbothang.getModel();
        model.removeAllElements();
        List<String> lst = luongcndao.getALLThangCC();
        for (String string : lst) {
            model.addElement(string);
        }
        model.addElement("");
        cbothang.setSelectedIndex(0);
    }

    void tinhLuongCN() {
        DecimalFormat df = new DecimalFormat("###,000");
        String maCn = txtMaCN.getText().trim();
        String tenCN = txtTenCN.getText().trim();
        int sosplamdc = Integer.parseInt(txtSoSPLamDuoc.getText().trim());
        int tongcalam = Integer.parseInt(txtSoCaDaLam.getText().trim());
        int thang = Integer.parseInt(cbothang.getSelectedItem().toString());
        int nam = Integer.parseInt(cbonam.getSelectedItem().toString());
        double luong = luongcndao.getALLLuong(maCn);
        CongNhan cn = new CongNhan(maCn, tenCN);
        LuongCongNhan lcn = new LuongCongNhan(cn, cn, sosplamdc, tongcalam, thang, nam, (float) luong);
        List<LuongCongNhan> lstluong = luongcndao.getALLLuongCN2();

      if (lstluong.contains(lcn)) {
            JOptionPane.showMessageDialog(this, "Công nhân đã được tính lương");
        } else {
            if (luongcndao.tinhLuongCN(lcn)) {
                readDatabaseTheoThangNam();
                int tong = tblLuong.getRowCount();
                for (int i = 0; i < tong - 1; i++) {
                    String ktr = modelLuong.getValueAt(i, 1).toString();
                    if (ktr.equals(txtMaCN.getText())) {
                        luongcndao.deleteLuongCN(modelLuong.getValueAt(i, 0).toString());
                    }
                }
                readDatabaseTheoThangNam();
                JOptionPane.showMessageDialog(this, "Tính lương thành công");
            }
        }

    }

    private void readDatabase() {
        modelLuong.setRowCount(0);
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        DecimalFormat df = new DecimalFormat("###,###.###");
        List<LuongCongNhan> lst = luongcndao.getALLLuongCN1();
        for (LuongCongNhan lg : lst) {
            Object[] row = {lg.getMaLuong(), lg.getMaCN().getMaCN(), lg.getTenCN().getTenCN(), lg.getSoSPLamDuoc(), lg.getTongCaLam(),
                lg.getThangLuong(), lg.getNamLuong(), df.format(lg.getTongLuong()) + " VNĐ"};
            modelLuong.addRow(row);
        }
    }
    
    private void readDatabaseLuongThang(){
        int thang = Integer.parseInt(cbothang.getSelectedItem().toString());
        int nam = Integer.parseInt(cbonam.getSelectedItem().toString());
        modelLuong.setRowCount(0);
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        DecimalFormat df = new DecimalFormat("###,###.###");
        List<LuongCongNhan> lst = luongcndao.getLuongCN1ThangNam(thang, nam);
        for (LuongCongNhan lg : lst) {
            Object[] row = {lg.getMaLuong(), lg.getMaCN().getMaCN(), lg.getTenCN().getTenCN(), lg.getSoSPLamDuoc(), lg.getTongCaLam(),
                lg.getThangLuong(), lg.getNamLuong(), df.format(lg.getTongLuong()) + " VNĐ"};
            modelLuong.addRow(row);
        }
    }

    private void readDatabaseTheoThangNam() {
        modelLuong.setRowCount(0);
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        DecimalFormat df = new DecimalFormat("###,###.###");
        List<LuongCongNhan> lst = luongcndao.getALLLuongCN1();
        for (LuongCongNhan lg : lst) {
            int thang = Integer.parseInt(cbothang.getSelectedItem().toString());
            int nam = Integer.parseInt(cbonam.getSelectedItem().toString());

            int thanglg = lg.getThangLuong();
            int namlg = lg.getNamLuong();
            if (nam == namlg && thang == thanglg) {
                Object[] row = {lg.getMaLuong(), lg.getMaCN().getMaCN(), lg.getTenCN().getTenCN(), lg.getSoSPLamDuoc(), lg.getTongCaLam(),
                    lg.getThangLuong(), lg.getNamLuong(), df.format(lg.getTongLuong()) + " VNĐ"};
                modelLuong.addRow(row);
            }

        }

    }

    public void xoa() {
        int row = tblLuong.getSelectedRow();
        int ques = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa ?", "Warning", JOptionPane.YES_NO_OPTION);
        if (ques == JOptionPane.YES_OPTION) {
            String maluong = tblLuong.getValueAt(row, 0).toString();
//            System.out.println(maluong);
            luongcndao.deleteLuongCN(maluong);
            if (txtbangluongnam.getText().toString().equals("Tất cả") && txtbangluongthang.getText().toString().equals("Tất cả")) {
                System.out.println("abc");
                readDatabase();
            } else {
                readDatabaseTheoThangNam();
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCN = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoSPLamDuoc = new javax.swing.JTextField();
        txtSoCaDaLam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTenCN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaCN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoCaTang = new javax.swing.JTextField();
        cbothang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbonam = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtbangluongthang = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtbangluongnam = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnXemLuongThangNam = new custom_button.MyButton();
        btnGetDS = new custom_button.MyButton();
        btnXemAllLuong = new custom_button.MyButton();
        myButton1 = new custom_button.MyButton();
        btnXoa = new custom_button.MyButton();
        btnIN = new custom_button.MyButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setText("LƯƠNG CÔNG NHÂN");
        add(jLabel1);
        jLabel1.setBounds(545, 6, 260, 26);
        add(jSeparator1);
        jSeparator1.setBounds(0, 832, 1, 10);

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Lương", "Mã CN", "Tên CN", "Số SP Làm Được", "Số Ca Đã Làm", "Tháng", "Năm", "Lương"
            }
        ));
        tblLuong.setPreferredSize(new java.awt.Dimension(600, 2000));
        tblLuong.setRowHeight(30);
        jScrollPane2.setViewportView(tblLuong);

        add(jScrollPane2);
        jScrollPane2.setBounds(7, 416, 1288, 310);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Danh Sách Công Nhân Có Lương Tháng");
        add(jLabel2);
        jLabel2.setBounds(680, 60, 290, 21);

        tblCN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblCN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MaCN", "TenCN"
            }
        ));
        tblCN.setRowHeight(25);
        tblCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCN);

        add(jScrollPane1);
        jScrollPane1.setBounds(730, 150, 568, 254);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Số Sản Phẩm Làm Được: ");
        add(jLabel3);
        jLabel3.setBounds(100, 210, 180, 17);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Số Ca Đã Làm: ");
        add(jLabel4);
        jLabel4.setBounds(450, 100, 110, 22);

        txtSoSPLamDuoc.setEditable(false);
        txtSoSPLamDuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoSPLamDuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoSPLamDuocActionPerformed(evt);
            }
        });
        add(txtSoSPLamDuoc);
        txtSoSPLamDuoc.setBounds(281, 195, 117, 32);

        txtSoCaDaLam.setEditable(false);
        txtSoCaDaLam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoCaDaLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoCaDaLamActionPerformed(evt);
            }
        });
        add(txtSoCaDaLam);
        txtSoCaDaLam.setBounds(570, 90, 93, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Mã CN:");
        add(jLabel7);
        jLabel7.setBounds(100, 90, 60, 22);

        txtTenCN.setEditable(false);
        txtTenCN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCNActionPerformed(evt);
            }
        });
        add(txtTenCN);
        txtTenCN.setBounds(171, 135, 227, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Tên CN:");
        add(jLabel8);
        jLabel8.setBounds(100, 150, 60, 22);

        txtMaCN.setEditable(false);
        txtMaCN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCNActionPerformed(evt);
            }
        });
        add(txtMaCN);
        txtMaCN.setBounds(170, 80, 225, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Số Ca Làm Tăng Ca:");
        add(jLabel9);
        jLabel9.setBounds(410, 150, 150, 17);

        txtSoCaTang.setEditable(false);
        txtSoCaTang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoCaTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoCaTangActionPerformed(evt);
            }
        });
        add(txtSoCaTang);
        txtSoCaTang.setBounds(570, 140, 91, 30);

        cbothang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbothang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbothangMouseClicked(evt);
            }
        });
        cbothang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbothangActionPerformed(evt);
            }
        });
        add(cbothang);
        cbothang.setBounds(960, 50, 72, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Năm");
        add(jLabel6);
        jLabel6.setBounds(1050, 60, 50, 22);

        cbonam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbonam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbonam);
        cbonam.setBounds(1090, 50, 78, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Bảng Lương Công Nhân Tháng");
        add(jLabel10);
        jLabel10.setBounds(30, 370, 240, 26);

        txtbangluongthang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add(txtbangluongthang);
        txtbangluongthang.setBounds(260, 370, 81, 26);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Năm");
        add(jLabel11);
        jLabel11.setBounds(360, 370, 40, 26);

        txtbangluongnam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add(txtbangluongnam);
        txtbangluongnam.setBounds(420, 370, 81, 26);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/support1.png"))); // NOI18N
        jLabel14.setText("Trợ giúp");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        add(jLabel14);
        jLabel14.setBounds(90, 0, 90, 30);

        btnXemLuongThangNam.setText("Xem Lương");
        btnXemLuongThangNam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXemLuongThangNam.setRadius(30);
        btnXemLuongThangNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLuongThangNamActionPerformed(evt);
            }
        });
        add(btnXemLuongThangNam);
        btnXemLuongThangNam.setBounds(970, 100, 130, 30);

        btnGetDS.setText("Lấy Danh Sách ");
        btnGetDS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnGetDS.setRadius(30);
        btnGetDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDSActionPerformed(evt);
            }
        });
        add(btnGetDS);
        btnGetDS.setBounds(790, 100, 140, 30);

        btnXemAllLuong.setText("Xem Tất Cả Lương");
        btnXemAllLuong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXemAllLuong.setRadius(30);
        btnXemAllLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemAllLuongActionPerformed(evt);
            }
        });
        add(btnXemAllLuong);
        btnXemAllLuong.setBounds(70, 280, 160, 50);

        myButton1.setText("Tính Lương");
        myButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        myButton1.setRadius(30);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        add(myButton1);
        myButton1.setBounds(270, 280, 140, 50);

        btnXoa.setText("Xóa Lương");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXoa.setRadius(30);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(440, 280, 130, 50);

        btnIN.setText("In");
        btnIN.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnIN.setRadius(30);
        btnIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINActionPerformed(evt);
            }
        });
        add(btnIN);
        btnIN.setBounds(600, 280, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoSPLamDuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoSPLamDuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoSPLamDuocActionPerformed

    private void txtSoCaDaLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCaDaLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCaDaLamActionPerformed

    private void txtTenCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCNActionPerformed

    private void txtMaCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCNActionPerformed

    private void txtSoCaTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoCaTangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoCaTangActionPerformed

    private void tblCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCNMouseClicked
        // TODO add your handling code here:
        clickTableCN();
        txtMaCN.setEnabled(true);
        txtSoCaDaLam.setEnabled(true);
        txtSoCaTang.setEnabled(true);
        txtTenCN.setEnabled(true);
        txtSoSPLamDuoc.setEnabled(true);
//        cbonam.setSelectedItem("");
//        cbothang.setSelectedItem("");
    }//GEN-LAST:event_tblCNMouseClicked

    private void cbothangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbothangActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbothangActionPerformed

    private void cbothangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbothangMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_cbothangMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        new HelpCNLuong().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnXemLuongThangNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLuongThangNamActionPerformed
        // TODO add your handling code here:
        readDatabaseLuongThang();
    }//GEN-LAST:event_btnXemLuongThangNamActionPerformed

    private void btnGetDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDSActionPerformed
        // TODO add your handling code here:
        modelLuong.setRowCount(0);
        readTableCN();
        String thang = cbothang.getSelectedItem().toString();
        txtbangluongthang.setText(thang);
        String nam = cbonam.getSelectedItem().toString();
        txtbangluongnam.setText(nam);
    }//GEN-LAST:event_btnGetDSActionPerformed

    private void btnXemAllLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemAllLuongActionPerformed
        // TODO add your handling code here:
        txtbangluongthang.setText("Tất cả");
        txtbangluongnam.setText("Tất cả");
        readDatabase();
    }//GEN-LAST:event_btnXemAllLuongActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        tinhLuongCN();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINActionPerformed
        // TODO add your handling code here:
        int thang =Integer.parseInt(cbothang.getSelectedItem().toString());
        int nam =Integer.parseInt(cbonam.getSelectedItem().toString());
        try{
             Hashtable map = new Hashtable();
        JasperReport rpt = JasperCompileManager.compileReport("src/myreport/rptLuongCN1.jrxml");
        map.put("thang", thang);
        map.put("nam", nam);
        Connection con = ConnectDB1.getConnection();
        JasperPrint p = JasperFillManager.fillReport(rpt, map, con);
        JasperViewer.viewReport(p,false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_button.MyButton btnGetDS;
    private custom_button.MyButton btnIN;
    private custom_button.MyButton btnXemAllLuong;
    private custom_button.MyButton btnXemLuongThangNam;
    private custom_button.MyButton btnXoa;
    private javax.swing.JComboBox<String> cbonam;
    private javax.swing.JComboBox<String> cbothang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private custom_button.MyButton myButton1;
    private javax.swing.JTable tblCN;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTextField txtMaCN;
    private javax.swing.JTextField txtSoCaDaLam;
    private javax.swing.JTextField txtSoCaTang;
    private javax.swing.JTextField txtSoSPLamDuoc;
    private javax.swing.JTextField txtTenCN;
    private javax.swing.JLabel txtbangluongnam;
    private javax.swing.JLabel txtbangluongthang;
    // End of variables declaration//GEN-END:variables
}
