/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import connect.ConnectDB1;
import dao.TrinhDoDao;
import entity.TrinhDo;
import java.io.ObjectOutput;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FrmTrinhDo extends javax.swing.JPanel {
    TrinhDoDao trinhDoDao;
    DefaultTableModel modelTD;
    /**
     * Creates new form pnTrinhDo
     */
    public FrmTrinhDo() {
        initComponents();
        try {
          ConnectDB1.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }
        trinhDoDao = new TrinhDoDao();
        modelTD = (DefaultTableModel) tblTrinhDo.getModel();
        readTable();
    }
    
    public void readTable(){
        modelTD.setRowCount(0);
        List<TrinhDo> lst = trinhDoDao.getAllTrinhDo();
        for (TrinhDo td : lst) {
            Object[] row = {td.getMaTrinhDo(),td.getTenTrinhDo(),td.getHesoLuong()};
            modelTD.addRow(row);
        }
    }
    
    public void clickTable(){
        int row = tblTrinhDo.getSelectedRow();
        txtMaTD.setText(modelTD.getValueAt(row, 0).toString());
        txtTenTD.setText(modelTD.getValueAt(row, 1).toString());
        txtHSL.setText(modelTD.getValueAt(row, 2).toString());
    }
    
     public void xoaTrang(){
        txtTenTD.setText("");
        txtMaTD.setText("");
        txtHSL.setText("");
    }

    public void themTD(){
        String maTD = txtMaTD.getText().trim();
        String tenTD = txtTenTD.getText().trim();
        double hsl = Double.parseDouble(txtHSL.getText().trim());
        TrinhDo pb = new TrinhDo(maTD, tenTD, hsl);
        List<TrinhDo> lst_check = trinhDoDao.getAllTrinhDo();
        if(lst_check.contains(pb)){
            JOptionPane.showMessageDialog(null, "Trùng mã");
        }else{
            if(trinhDoDao.createTrinhDo(pb)){
                readTable();
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                xoaTrang();
            }
            else{
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
                xoaTrang();
            }
        }
    }
    
    public void suaTD(){
        int row = tblTrinhDo.getSelectedRow();
        String maTD = txtMaTD.getText().trim();
        String tenTD = txtTenTD.getText().trim();
        double hsl = Double.parseDouble(txtHSL.getText().trim());
        TrinhDo pb = new TrinhDo(maTD, tenTD, hsl);
        int ques = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa","Attention!",JOptionPane.YES_NO_OPTION);
        if(ques==JOptionPane.YES_OPTION){
            if(trinhDoDao.updateTrinhDo(pb)){
                readTable();
                JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            }
            else{
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
            }
        }
        xoaTrang();
    }
    
    public void xoaTD(){
        int row = tblTrinhDo.getSelectedRow();
	int ques = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa ?", "Warning", JOptionPane.YES_NO_OPTION);
	if(ques==JOptionPane.YES_OPTION) {
            String ma = (String) tblTrinhDo.getValueAt(row, 0);
		trinhDoDao.deleteTrinhDo(ma);
		readTable();
		}
	xoaTrang();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaTD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenTD = new javax.swing.JTextField();
        btnThemTD = new custom_button.MyButton();
        btnSuaTD = new custom_button.MyButton();
        jLabel4 = new javax.swing.JLabel();
        txtHSL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrinhDo = new javax.swing.JTable();
        btnXoaTD = new custom_button.MyButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TRÌNH ÐỘ");
        add(jLabel1);
        jLabel1.setBounds(520, 43, 140, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Mã Trình Độ:");
        add(jLabel2);
        jLabel2.setBounds(270, 120, 140, 20);

        txtMaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTDActionPerformed(evt);
            }
        });
        add(txtMaTD);
        txtMaTD.setBounds(410, 110, 180, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Tên Trình Độ:");
        add(jLabel3);
        jLabel3.setBounds(270, 200, 140, 20);

        txtTenTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTDActionPerformed(evt);
            }
        });
        add(txtTenTD);
        txtTenTD.setBounds(410, 190, 180, 40);

        btnThemTD.setText("Thêm");
        btnThemTD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemTD.setRadius(45);
        btnThemTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTDActionPerformed(evt);
            }
        });
        add(btnThemTD);
        btnThemTD.setBounds(770, 110, 140, 40);

        btnSuaTD.setText("Sửa");
        btnSuaTD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaTD.setRadius(45);
        btnSuaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTDActionPerformed(evt);
            }
        });
        add(btnSuaTD);
        btnSuaTD.setBounds(770, 260, 140, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Hệ Số Lương:");
        add(jLabel4);
        jLabel4.setBounds(270, 270, 140, 20);

        txtHSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHSLActionPerformed(evt);
            }
        });
        add(txtHSL);
        txtHSL.setBounds(410, 260, 180, 40);

        tblTrinhDo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Trình Độ", "Tên Trình Độ", "Hệ Số Lương"
            }
        ));
        tblTrinhDo.setRowHeight(30);
        tblTrinhDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrinhDoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTrinhDo);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 330, 940, 360);

        btnXoaTD.setText("Xóa");
        btnXoaTD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaTD.setRadius(45);
        btnXoaTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTDActionPerformed(evt);
            }
        });
        add(btnXoaTD);
        btnXoaTD.setBounds(770, 190, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTDActionPerformed

    private void txtTenTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTDActionPerformed

    private void btnThemTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTDActionPerformed
        // TODO add your handling code here:
        themTD();
    }//GEN-LAST:event_btnThemTDActionPerformed

    private void btnSuaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTDActionPerformed
        // TODO add your handling code here:
        suaTD();
    }//GEN-LAST:event_btnSuaTDActionPerformed

    private void txtHSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHSLActionPerformed

    private void btnXoaTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTDActionPerformed
        // TODO add your handling code here:
        xoaTD();
    }//GEN-LAST:event_btnXoaTDActionPerformed

    private void tblTrinhDoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrinhDoMouseClicked
        // TODO add your handling code here:
        clickTable();
    }//GEN-LAST:event_tblTrinhDoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_button.MyButton btnSuaTD;
    private custom_button.MyButton btnThemTD;
    private custom_button.MyButton btnXoaTD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrinhDo;
    private javax.swing.JTextField txtHSL;
    private javax.swing.JTextField txtMaTD;
    private javax.swing.JTextField txtTenTD;
    // End of variables declaration//GEN-END:variables
}
